[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://api.interpipe.co.zw"
  VITE_API_BASE_PATH = "/api"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable CORS headers to allow interaction with the API
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.interpipe.co.zw https://www.interpipe.co.zw; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self' data:;" 